name: Folder Listener
on:
  push:
    branches:
      # - main         #to be changed to master
      - feature/initial

  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  folder-listener:
    runs-on: ubuntu-latest
    env:
        LISTENING_FOLDER : api/app/controllers
        NOTIFICATION_FROM: ALVDIGITAL Systems (API)
        NOTIFICATION_SUBJECT: ALV API Controllers-GitHub Updated
        NOTIFICATION_TO_DEFAULT: kumvijaya@gmail.com # service@alvdigital.com
        NOTIFICATION_EMAIL_IDS: vijaik.nd@gmail.com,vishali.nagathevan@gmail.com,kumvijaya@gmail.com,alagu.rar@gmail.com
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      - name: Get changed files in ${{ env. LISTENING_FOLDER }}
        if: github.event.pull_request.merged == true
        id: changed-files-specific
        uses: tj-actions/changed-files@v37
        with:
            files: ${{ env.LISTENING_FOLDER }}
 
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files in ${{ env.LISTENING_FOLDER }}
        if: steps.changed-files-specific.outputs.any_changed == 'true' && github.event.pull_request.merged == true
        run: |
          file_changed_html='<ul>'
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
            file_changed_html="${file_changed_html}<li>${file}</li>"
          done
          file_changed_html="${file_changed_html}</ul>"
          echo "FILES_CHANGED_HTML=$file_changed_html" >> $GITHUB_ENV

      - name: Send email
        if: steps.changed-files-specific.outputs.any_changed == 'true' && github.event.pull_request.merged == true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.SMTP_USER}}
          # Optional (recommended) mail server password:
          password: ${{secrets.SMTP_PASSWORD}}
          # Required mail subject:
          subject: ${{ env.NOTIFICATION_SUBJECT }}
          # Required recipients addresses:
          to: ${{ env.NOTIFICATION_TO_DEFAULT }}
          # Optional recipients addresses:
          bcc: ${{ env.NOTIFICATION_EMAIL_IDS }}
          # Required sender full name (address can be skipped):
          from: ${{ env.NOTIFICATION_FROM }}
          # Optional plain body:
          html_body: |
            <b>Files changed: ${{ steps.changed-files-specific.outputs.all_changed_files_count }}</b>
            <hr>
            ${{ env.FILES_CHANGED_HTML }}
            <br>
            <b>Commit Comment</b>
            <hr>
            <pre>

            ${{ github.event.pull_request.commits }}


            <b>This is an automated email. If you have questions about the above, please email to service@alvdigital.com</b>
            </pre>

          priority: high
    